### ISSUE TITLE
Install Tesla battery modules

### ISSUE THREAD

**Issue by kklem0** [kklem0/Off-Grid-Smart-RV#8]
Install Tesla battery modules under the beds in the sleeping room.

**Comment by kklem0** [comment]
Idea is to have 8 battery modules, 2 in series x 4 parallel, so we can have a 48v DC system.
min 40v (need to double check), max 48.2v, 4.02v per cell.

**Comment by clementhk** [comment]
Just found out that the Battery Medic wouldn't work in a 48v series, ordering Batrium WatchMonPlus instead.
Cost is 5,000.00 each and we need 4 of them, 1 for each series.

**Comment by kklem0** [comment]
Batrium just launched MultiMon 8, which makes it possible to parallel 15 12s.
It's a slave of WatchMonPlus so we need to get 1 WatchMonPlus and 3 MM8 in our system.
Cost of MM8 is 2,200 NOK. 😊
So for BMS the cost is 5,000 + (2,000 x 3) = 11,000 NOK. Almost half the price!

**Comment by kklem0** [comment]
Bought another 4 battery modules, goal is to have 8 in total.

**Comment by kklem0** [comment]
![AF0C53B9-BDE4-4326-B687-BB567AAF6CA0](https://user-images.githubusercontent.com/3030930/77385114-7e961900-6d87-11ea-9b23-0debc3e1e1a4.jpeg)

Works

**Comment by kklem0** [comment]
Installed 2 modules, 6 will come next week but will open another issue for that as it will use MM8 instead of WM5.
